version: '3.9'

services:

  python-app:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=Registration
      - PG_HOST=pgdb
      - PG_PORT=5432
    depends_on:
      - pgdb


  pgdb:
    image: postgres:16.1
    container_name: pgdb
    environment:
      POSTGRES_DB: Registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdb_data:/var/lib/postgresql/data



volumes:
  pgdb_data: {}
